Implement POST /api/articles/:id/comments
SamPetcher/cautious-journey pull request #6
Opened 2022-12-15 14:59 UTC by SamPetcher

2022-12-15 15:50 UTC, Poonam-raj requested changes
Hey Sam, few more tests needed and then you're rocking and rolling with this PR - amend the code and throw it our way again

2022-12-15 15:50 UTC, Poonam-raj commented on __tests__/app.test.js
> +		.expect(200)
Posts will be a 201 Created status code, pls amend 👍🏾

2022-12-15 15:50 UTC, Poonam-raj commented on __tests__/app.test.js
> +				expect(comment.body).toEqual(expect.objectContaining({
you should be sending data back on the comment key, e.g.
```
{ body: { comment: { comment_id: ...} } }
```

2022-12-15 15:50 UTC, Poonam-raj commented on __tests__/app.test.js
> +			expect(comment.body.msg).toEqual("Invalid article")
This error message doesn't match what's wrong with the posted body (user being wrong). Would be worth amending this message to either be vaguer or reflect the fact it;s a malformed body

2022-12-15 15:50 UTC, Poonam-raj commented on __tests__/app.test.js
> +		})
More tests worth including for this endpoint:
- 201 when other properties are in the response body (ignores unnecessary properties)
- 400 when required fields are missing

2022-12-15 15:50 UTC, Poonam-raj commented on controllers/errors.controllers.js
> +		res.status(404).send({ msg:  "Invalid article" })
I think this is the error that could reflect the fact it's actually invalid username possibly

2022-12-16 11:43 UTC, B7Bprog approved these changes
Hey Sam, please check my comment and fix that typo, then feel free to merge! 👍

2022-12-16 11:43 UTC, B7Bprog commented on __tests__/app.test.js
> +	it('Should 404 when the user doesnt provide the correct field...', () => {
Please change this code to 400 in the test description.

2022-12-16 13:34 UTC, merged